# Generated by Django 5.0.3 on 2024-04-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(choices=[(1, 'Small Box'), (2, 'Medium Box'), (3, 'Large Box'), (4, 'No Box'), (5, 'Own Box'), (6, 'Bag')], default=None)),
                ('price', models.IntegerField(choices=[(1, 'Standard Price'), (2, 'High Price')], default=None)),
                ('dropship', models.BooleanField(blank=True)),
                ('envelope', models.BooleanField(blank=True)),
                ('finalPrice', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourierManager.courier')),
            ],
        ),
    ]
