# Generated by Django 5.0.3 on 2024-04-24 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceManager', '0001_initial'),
        ('StockManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockManager.product'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceManager.servicelist'),
        ),
        migrations.AddField(
            model_name='labelchangeservice',
            name='newProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newProduct', to='StockManager.product'),
        ),
    ]
