# Generated by Django 5.0.3 on 2024-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyCode', models.CharField(max_length=50)),
                ('companyAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('directorName', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('weChat', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('vatNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('businessLicence', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
